/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 src/assets/models/donut.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/donut.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Sphere.geometry} material={materials.Sprinkles} position={[3.315, 2.428, 2.165]} rotation={[0.298, 0, 0]} scale={6.468} />
      <mesh geometry={nodes.Cylinder.geometry} material={materials.Sprinkles} position={[3.483, 2.488, 2.056]} rotation={[0.298, 0, 0]} scale={6.468} />
      <mesh geometry={nodes.Cylinder008.geometry} material={materials.Sprinkles} position={[-2, 3.067, -1.372]} rotation={[-2.743, 0.312, 0.389]} scale={[109.134, 109.135, 109.135]} />
      <mesh geometry={nodes.Cylinder009.geometry} material={materials.Sprinkles} position={[1.12, 1.705, 3.374]} rotation={[3.11, -1.022, 1.77]} scale={[109.135, 109.134, 109.135]} />
      <mesh geometry={nodes.Cylinder010.geometry} material={materials.Sprinkles} position={[-4.023, 2.28, 0.02]} rotation={[2.259, -0.876, 2.61]} scale={109.135} />
      <mesh geometry={nodes.Cylinder011.geometry} material={materials.Sprinkles} position={[-3.552, 2.472, 0.053]} rotation={[0.455, -0.372, 1.916]} scale={109.135} />
      <mesh geometry={nodes.Cylinder012.geometry} material={materials.Sprinkles} position={[-1.275, 0.741, 4.173]} rotation={[-2.16, 0.33, -2.691]} scale={109.135} />
      <mesh geometry={nodes.Cylinder023.geometry} material={materials.Sprinkles} position={[1.639, 1.838, 3.102]} rotation={[0.242, 0.246, -2.281]} scale={[109.135, 109.135, 109.134]} />
      <mesh geometry={nodes.Cylinder027.geometry} material={materials.Sprinkles} position={[-1, 1.442, 1.499]} rotation={[-0.373, 0.029, 1.954]} scale={109.135} />
      <mesh geometry={nodes.Cylinder036.geometry} material={materials.Sprinkles} position={[-2.82, 2.935, -3.066]} rotation={[-0.999, 0.5, 2.805]} scale={109.135} />
      <mesh geometry={nodes.Cylinder038.geometry} material={materials.Sprinkles} position={[-2.429, 2.412, 0.135]} rotation={[0.479, -0.064, -1.671]} scale={[109.134, 109.134, 109.135]} />
      <mesh geometry={nodes.Cylinder039.geometry} material={materials.Sprinkles} position={[-0.868, 3.424, -2.647]} rotation={[2.744, 1.02, -2.396]} scale={[109.134, 109.135, 109.134]} />
      <mesh geometry={nodes.Cylinder045.geometry} material={materials.Sprinkles} position={[-0.112, 0.109, 4.749]} rotation={[2.024, 1.359, -0.44]} scale={[109.134, 109.135, 109.134]} />
      <mesh geometry={nodes.Cylinder048.geometry} material={materials.Sprinkles} position={[3.107, 2.609, 0.422]} rotation={[-3.018, 0.228, 2.455]} scale={109.134} />
      <mesh geometry={nodes.Cylinder049.geometry} material={materials.Sprinkles} position={[3.683, 2.531, 0.593]} rotation={[0.075, 0.187, 3.07]} scale={109.135} />
      <mesh geometry={nodes.Cylinder058.geometry} material={materials.Sprinkles} position={[-1.988, 3.289, -2.037]} rotation={[0.309, 0.149, -0.117]} scale={[109.134, 109.135, 109.135]} />
      <mesh geometry={nodes.Cylinder063.geometry} material={materials.Sprinkles} position={[-0.131, 0.666, 4.536]} rotation={[0.902, 1.142, -1.223]} scale={109.134} />
      <mesh geometry={nodes.Cylinder064.geometry} material={materials.Sprinkles} position={[-1.597, 3.294, -2.016]} rotation={[-2.872, -0.794, -1.775]} scale={109.134} />
      <mesh geometry={nodes.Cylinder070.geometry} material={materials.Sprinkles} position={[1.117, 1.823, 2.501]} rotation={[0.49, -1.197, -3.019]} scale={[109.135, 109.135, 109.134]} />
      <mesh geometry={nodes.Cylinder071.geometry} material={materials.Sprinkles} position={[-2.648, 1.807, 1.867]} rotation={[0.7, 1.411, 0.717]} scale={109.134} />
      <mesh geometry={nodes.Cylinder072.geometry} material={materials.Sprinkles} position={[3.94, 2.732, -2.334]} rotation={[-0.494, -0.773, -0.877]} scale={109.134} />
      <mesh geometry={nodes.Cylinder079.geometry} material={materials.Sprinkles} position={[0.5, 1.601, 2.15]} rotation={[-0.504, -0.153, 2.94]} scale={109.134} />
      <mesh geometry={nodes.Cylinder083.geometry} material={materials.Sprinkles} position={[-0.879, 2.15, -0.916]} rotation={[1.849, 0.643, -0.912]} scale={109.135} />
      <mesh geometry={nodes.Cylinder087.geometry} material={materials.Sprinkles} position={[-1.862, 2.456, -0.42]} rotation={[1.182, 0.606, 0.402]} scale={109.134} />
      <mesh geometry={nodes.Cylinder090.geometry} material={materials.Sprinkles} position={[4.042, 2.327, 0.861]} rotation={[0.087, 0.008, -3.047]} scale={[109.135, 109.135, 109.134]} />
      <mesh geometry={nodes.Cylinder098.geometry} material={materials.Sprinkles} position={[3.152, 1.831, 2.774]} rotation={[-3.06, 1.177, 1.197]} scale={[109.135, 109.134, 109.134]} />
      <mesh geometry={nodes.Cylinder101.geometry} material={materials.Sprinkles} position={[1.55, 2.465, -0.797]} rotation={[-2.492, -0.125, -2.247]} scale={109.134} />
      <mesh geometry={nodes.Cylinder104.geometry} material={materials.Sprinkles} position={[2.754, 2.233, 1.891]} rotation={[-2.827, 0.484, 0.811]} scale={109.134} />
      <mesh geometry={nodes.Cylinder106.geometry} material={materials.Sprinkles} position={[1.044, 3.368, -3.346]} rotation={[-0.025, 1.294, 1.388]} scale={109.134} />
      <mesh geometry={nodes.Cylinder107.geometry} material={materials.Sprinkles} position={[4.064, 1.966, 1.71]} rotation={[0.759, 0.308, -1.536]} scale={[109.135, 109.134, 109.135]} />
      <mesh geometry={nodes.Cylinder110.geometry} material={materials.Sprinkles} position={[-2.818, 0.748, 3.415]} rotation={[2.21, -0.912, 0.43]} scale={109.135} />
      <mesh geometry={nodes.Cylinder117.geometry} material={materials.Sprinkles} position={[-2.236, 0.995, 3.521]} rotation={[-2.404, -0.547, 0.697]} scale={109.134} />
      <mesh geometry={nodes.Cylinder118.geometry} material={materials.Sprinkles} position={[4.123, 1.586, 2.233]} rotation={[0.224, -0.467, -2.734]} scale={[109.134, 109.135, 109.134]} />
      <mesh geometry={nodes.Cylinder119.geometry} material={materials.Sprinkles} position={[1.333, 3.404, -2.576]} rotation={[-2.104, 1.279, -1.581]} scale={109.135} />
      <mesh geometry={nodes.Cylinder125.geometry} material={materials.Sprinkles} position={[-0.361, 3.429, -2.762]} rotation={[0.052, -0.113, 1.598]} scale={[109.135, 109.134, 109.135]} />
      <mesh geometry={nodes.Cylinder129.geometry} material={materials.Sprinkles} position={[0.802, 3.242, -2.001]} rotation={[0.393, -0.26, -1.879]} scale={[109.134, 109.134, 109.135]} />
      <mesh geometry={nodes.Cylinder137.geometry} material={materials.Sprinkles} position={[-1.794, 1.101, 3.618]} rotation={[-0.996, 1.297, 0.293]} scale={[109.135, 109.134, 109.134]} />
      <mesh geometry={nodes.Cylinder138.geometry} material={materials.Sprinkles} position={[-1.082, 3.339, -2.191]} rotation={[-2.779, 0.731, 0.943]} scale={[109.134, 109.135, 109.134]} />
      <mesh geometry={nodes.Cylinder139.geometry} material={materials.Sprinkles} position={[2.83, 3.227, -2.326]} rotation={[-0.051, 0.502, -2.553]} scale={109.134} />
      <mesh geometry={nodes.Cylinder141.geometry} material={materials.Sprinkles} position={[2.381, 2.498, 0.054]} rotation={[2.436, -1.346, -1.753]} scale={109.135} />
      <mesh geometry={nodes.Cylinder148.geometry} material={materials.Sprinkles} position={[-3.558, 1.045, 2.647]} rotation={[2.006, -0.718, 0.963]} scale={109.135} />
      <mesh geometry={nodes.Cylinder154.geometry} material={materials.Sprinkles} position={[1.987, 3.209, -1.766]} rotation={[-0.498, -1.321, 2.493]} scale={[109.134, 109.135, 109.134]} />
      <mesh geometry={nodes.Cylinder155.geometry} material={materials.Sprinkles} position={[1.682, 3.052, -1.489]} rotation={[-1.438, 1.419, 0.449]} scale={[109.135, 109.135, 109.134]} />
      <mesh geometry={nodes.Cylinder158.geometry} material={materials.Sprinkles} position={[1.427, 1.592, 3.64]} rotation={[0.487, 0.466, -2.738]} scale={109.135} />
      <mesh geometry={nodes.Cylinder160.geometry} material={materials.Sprinkles} position={[1.442, 2.696, -1.1]} rotation={[0.545, 0.7, -0.797]} scale={[109.135, 109.134, 109.135]} />
      <mesh geometry={nodes.Cylinder001.geometry} material={materials.Sprinkles} position={[3.509, 2.497, 2.044]} rotation={[0.298, 0, 0]} scale={6.468} />
      <mesh geometry={nodes.Cylinder004.geometry} material={materials.Sprinkles} position={[-3.907, 2.474, -0.382]} rotation={[-2.855, 0.087, 1.207]} scale={109.134} />
      <mesh geometry={nodes.Cylinder005.geometry} material={materials.Sprinkles} position={[-1.412, 1.544, 2.957]} rotation={[0.602, -0.928, 1.212]} scale={109.134} />
      <mesh geometry={nodes.Cylinder016.geometry} material={materials.Sprinkles} position={[-1.414, 2.385, -0.723]} rotation={[1.58, 0.578, -0.22]} scale={[109.134, 109.135, 109.135]} />
      <mesh geometry={nodes.Cylinder025.geometry} material={materials.Sprinkles} position={[0.706, 3.281, -3.71]} rotation={[2.758, 0.531, 0.387]} scale={[109.134, 109.135, 109.135]} />
      <mesh geometry={nodes.Cylinder026.geometry} material={materials.Sprinkles} position={[-0.588, 3.335, -3.606]} rotation={[-0.046, -0.149, -0.229]} scale={[109.134, 109.135, 109.135]} />
      <mesh geometry={nodes.Cylinder029.geometry} material={materials.Sprinkles} position={[3.794, 2.839, -0.951]} rotation={[-1.854, -1.302, -2.937]} scale={109.135} />
      <mesh geometry={nodes.Cylinder033.geometry} material={materials.Sprinkles} position={[-3.678, 1.473, 2.009]} rotation={[2.391, -1.232, -0.695]} scale={[109.135, 109.135, 109.134]} />
      <mesh geometry={nodes.Cylinder040.geometry} material={materials.Sprinkles} position={[3.808, 2.253, 1.361]} rotation={[0.223, -0.252, 1.544]} scale={109.134} />
      <mesh geometry={nodes.Cylinder041.geometry} material={materials.Sprinkles} position={[1.563, 3.272, -1.994]} rotation={[0.211, 0.474, 2.603]} scale={109.134} />
      <mesh geometry={nodes.Cylinder043.geometry} material={materials.Sprinkles} position={[-2.451, 3.142, -3.04]} rotation={[-0.657, 0.555, 2.642]} scale={109.134} />
      <mesh geometry={nodes.Cylinder047.geometry} material={materials.Sprinkles} position={[2.185, 2.755, -0.72]} rotation={[-2.793, -0.346, 1.877]} scale={109.134} />
      <mesh geometry={nodes.Cylinder051.geometry} material={materials.Sprinkles} position={[1.327, 3.124, -1.706]} rotation={[2.584, -1.322, 2.833]} scale={[109.135, 109.135, 109.134]} />
      <mesh geometry={nodes.Cylinder053.geometry} material={materials.Sprinkles} position={[2.747, 2.632, 0.084]} rotation={[-3.032, -0.092, -2.677]} scale={109.135} />
      <mesh geometry={nodes.Cylinder057.geometry} material={materials.Sprinkles} position={[2.529, 2.46, 0.419]} rotation={[2.723, -0.83, 3.045]} scale={109.135} />
      <mesh geometry={nodes.Cylinder062.geometry} material={materials.Sprinkles} position={[1.106, 2.814, -1.35]} rotation={[-2.533, -0.244, 2.658]} scale={109.135} />
      <mesh geometry={nodes.Cylinder065.geometry} material={materials.Sprinkles} position={[0.852, 2.411, -1.121]} rotation={[0.025, 1.37, -0.159]} scale={109.134} />
      <mesh geometry={nodes.Cylinder068.geometry} material={materials.Sprinkles} position={[1.805, 1.949, 1.319]} rotation={[-0.769, 1.062, 0.496]} scale={109.135} />
      <mesh geometry={nodes.Cylinder081.geometry} material={materials.Sprinkles} position={[0.401, 1.924, -1.074]} rotation={[1.199, 0.795, -0.193]} scale={[109.134, 109.135, 109.135]} />
      <mesh geometry={nodes.Cylinder086.geometry} material={materials.Sprinkles} position={[0.376, 1.623, 3.393]} rotation={[1.93, -1.144, 1.428]} scale={109.134} />
      <mesh geometry={nodes.Cylinder102.geometry} material={materials.Sprinkles} position={[-1.784, 3.26, -3.343]} rotation={[2.216, -1.152, 0.995]} scale={[109.135, 109.135, 109.134]} />
      <mesh geometry={nodes.Cylinder103.geometry} material={materials.Sprinkles} position={[-2.349, 0.668, 3.737]} rotation={[0.966, 0.656, 1.012]} scale={[109.135, 109.134, 109.134]} />
      <mesh geometry={nodes.Cylinder108.geometry} material={materials.Sprinkles} position={[1.176, 3.416, -2.943]} rotation={[2.758, 1.221, -2.448]} scale={[109.135, 109.134, 109.134]} />
      <mesh geometry={nodes.Cylinder115.geometry} material={materials.Sprinkles} position={[-0.496, 1.406, 3.666]} rotation={[-2.628, -0.307, 0.745]} scale={[109.134, 109.135, 109.135]} />
      <mesh geometry={nodes.Cylinder122.geometry} material={materials.Sprinkles} position={[-1.681, 0.802, 3.96]} rotation={[1.895, -1.204, 2.918]} scale={[109.135, 109.135, 109.134]} />
      <mesh geometry={nodes.Cylinder127.geometry} material={materials.Sprinkles} position={[-1.531, 1.634, 0.702]} rotation={[-1.012, -0.641, 1.3]} scale={109.135} />
      <mesh geometry={nodes.Cylinder128.geometry} material={materials.Sprinkles} position={[-1.897, 3.351, -2.807]} rotation={[-2.133, 1.458, 2.381]} scale={[109.134, 109.135, 109.134]} />
      <mesh geometry={nodes.Cylinder145.geometry} material={materials.Sprinkles} position={[-2.622, 1.185, 3.097]} rotation={[-1.687, 0.673, -0.804]} scale={109.134} />
      <mesh geometry={nodes.Cylinder150.geometry} material={materials.Sprinkles} position={[-0.138, 2.384, -1.227]} rotation={[-2.129, 0.274, 2.432]} scale={[109.135, 109.134, 109.135]} />
      <mesh geometry={nodes.Cylinder151.geometry} material={materials.Sprinkles} position={[2.425, 3.183, -1.656]} rotation={[-3.126, 0.354, 2.73]} scale={109.135} />
      <mesh geometry={nodes.Cylinder152.geometry} material={materials.Sprinkles} position={[-3.177, 2.372, 0.457]} rotation={[-2.964, -0.482, 2.305]} scale={[109.135, 109.134, 109.135]} />
      <mesh geometry={nodes.Cylinder153.geometry} material={materials.Sprinkles} position={[-0.136, 1.623, 3.129]} rotation={[-1.078, 1.274, -1.675]} scale={[109.135, 109.135, 109.134]} />
      <mesh geometry={nodes.Cylinder164.geometry} material={materials.Sprinkles} position={[2.46, 2.148, 2.153]} rotation={[-2.894, 0.172, 1.343]} scale={[109.135, 109.134, 109.135]} />
      <mesh geometry={nodes.Cylinder002.geometry} material={materials.Sprinkles} position={[3.533, 2.508, 2.031]} rotation={[0.298, 0, 0]} scale={6.468} />
      <mesh geometry={nodes.Cylinder014.geometry} material={materials.Sprinkles} position={[-2.765, 1.464, 2.599]} rotation={[0.724, -0.871, -2.941]} scale={[109.135, 109.135, 109.134]} />
      <mesh geometry={nodes.Cylinder015.geometry} material={materials.Sprinkles} position={[-1.741, 1.638, 2.5]} rotation={[0.202, -0.077, 1.654]} scale={[109.135, 109.134, 109.135]} />
      <mesh geometry={nodes.Cylinder017.geometry} material={materials.Sprinkles} position={[-1.079, 1.627, 2.526]} rotation={[0.073, 0.607, -1.554]} scale={[109.135, 109.134, 109.134]} />
      <mesh geometry={nodes.Cylinder018.geometry} material={materials.Sprinkles} position={[-1.185, 1.05, 3.933]} rotation={[1.809, -1.214, -0.043]} scale={109.134} />
      <mesh geometry={nodes.Cylinder019.geometry} material={materials.Sprinkles} position={[2.402, 3.261, -3.021]} rotation={[-0.322, 1.209, -2.464]} scale={[109.135, 109.135, 109.134]} />
      <mesh geometry={nodes.Cylinder020.geometry} material={materials.Sprinkles} position={[3.255, 2.231, 1.826]} rotation={[-2.955, 0.284, 2.091]} scale={109.134} />
      <mesh geometry={nodes.Cylinder021.geometry} material={materials.Sprinkles} position={[-3.022, 2.523, 0.111]} rotation={[0.186, 0.584, 2.727]} scale={[109.134, 109.135, 109.134]} />
      <mesh geometry={nodes.Cylinder022.geometry} material={materials.Sprinkles} position={[-2.96, 1.625, 2.203]} rotation={[0.409, -0.059, 2.049]} scale={[109.134, 109.134, 109.135]} />
      <mesh geometry={nodes.Cylinder028.geometry} material={materials.Sprinkles} position={[-0.83, 3.419, -3.158]} rotation={[0.04, -0.408, 0.836]} scale={[109.134, 109.134, 109.135]} />
      <mesh geometry={nodes.Cylinder032.geometry} material={materials.Sprinkles} position={[-2.185, 3.077, -3.46]} rotation={[0.776, -1.037, 2.372]} scale={[109.135, 109.135, 109.134]} />
      <mesh geometry={nodes.Cylinder037.geometry} material={materials.Sprinkles} position={[1.18, 1.812, 2.983]} rotation={[-3.038, -0.518, -1.577]} scale={109.135} />
      <mesh geometry={nodes.Cylinder042.geometry} material={materials.Sprinkles} position={[0.536, 3.421, -3.104]} rotation={[3.081, 0.27, 1.438]} scale={[109.134, 109.134, 109.135]} />
      <mesh geometry={nodes.Cylinder046.geometry} material={materials.Sprinkles} position={[-1.001, 1.302, 3.672]} rotation={[-2.587, -0.516, -0.744]} scale={109.134} />
      <mesh geometry={nodes.Cylinder050.geometry} material={materials.Sprinkles} position={[-3.771, 2.645, -0.831]} rotation={[-0.695, 0.92, -2.129]} scale={[109.135, 109.135, 109.134]} />
      <mesh geometry={nodes.Cylinder052.geometry} material={materials.Sprinkles} position={[-1.721, 1.723, 1.717]} rotation={[-2.778, -1.061, 2.182]} scale={109.135} />
      <mesh geometry={nodes.Cylinder054.geometry} material={materials.Sprinkles} position={[-2.315, 3.277, -2.573]} rotation={[0.087, 0.702, 0.127]} scale={[109.134, 109.135, 109.134]} />
      <mesh geometry={nodes.Cylinder056.geometry} material={materials.Sprinkles} position={[0.687, 1.74, 2.959]} rotation={[3.014, -0.478, -2.706]} scale={109.135} />
      <mesh geometry={nodes.Cylinder059.geometry} material={materials.Sprinkles} position={[2.166, 2.15, 1.359]} rotation={[0.596, -0.865, -0.923]} scale={[109.135, 109.135, 109.134]} />
      <mesh geometry={nodes.Cylinder061.geometry} material={materials.Sprinkles} position={[1.653, 1.829, 0.149]} rotation={[2.267, -0.666, -2.987]} scale={109.134} />
      <mesh geometry={nodes.Cylinder066.geometry} material={materials.Sprinkles} position={[-1.512, 1.842, -0.006]} rotation={[-2.91, 0.445, -0.256]} scale={[109.134, 109.135, 109.135]} />
      <mesh geometry={nodes.Cylinder067.geometry} material={materials.Sprinkles} position={[1.173, 1.749, 1.959]} rotation={[-0.979, 0.999, -2.8]} scale={109.134} />
      <mesh geometry={nodes.Cylinder069.geometry} material={materials.Sprinkles} position={[3.114, 2.508, 0.828]} rotation={[-2.799, 0.482, -0.172]} scale={109.134} />
      <mesh geometry={nodes.Cylinder075.geometry} material={materials.Sprinkles} position={[-0.827, 1.5, 3.322]} rotation={[0.515, -0.396, -0.918]} scale={109.135} />
      <mesh geometry={nodes.Cylinder077.geometry} material={materials.Sprinkles} position={[-2.825, 2.904, -0.846]} rotation={[-0.574, 1.219, -1.936]} scale={109.135} />
      <mesh geometry={nodes.Cylinder078.geometry} material={materials.Sprinkles} position={[0.295, 2.493, -1.274]} rotation={[1.109, -0.16, -1.324]} scale={[109.135, 109.134, 109.134]} />
      <mesh geometry={nodes.Cylinder080.geometry} material={materials.Sprinkles} position={[-0.67, 1.616, 2.825]} rotation={[-0.126, 1.369, -1.241]} scale={[109.135, 109.135, 109.134]} />
      <mesh geometry={nodes.Cylinder085.geometry} material={materials.Sprinkles} position={[3.277, 3.099, -1.865]} rotation={[-3.12, 0.947, -0.306]} scale={109.135} />
      <mesh geometry={nodes.Cylinder088.geometry} material={materials.Sprinkles} position={[2.483, 1.728, 3.248]} rotation={[-2.913, 0.506, 3.09]} scale={109.134} />
      <mesh geometry={nodes.Cylinder089.geometry} material={materials.Sprinkles} position={[3.56, 1.736, 2.62]} rotation={[-2.352, -0.804, -3.06]} scale={109.135} />
      <mesh geometry={nodes.Cylinder095.geometry} material={materials.Sprinkles} position={[-0.706, 1.607, 2.395]} rotation={[-0.221, -0.552, -2.326]} scale={109.135} />
      <mesh geometry={nodes.Cylinder097.geometry} material={materials.Sprinkles} position={[-0.683, 1.091, 4.064]} rotation={[-3.099, -1.049, 2.631]} scale={109.135} />
      <mesh geometry={nodes.Cylinder100.geometry} material={materials.Sprinkles} position={[-3.96, 1.8, 1.184]} rotation={[-0.726, 1.063, -2.766]} scale={[109.134, 109.135, 109.134]} />
      <mesh geometry={nodes.Cylinder105.geometry} material={materials.Sprinkles} position={[4.694, 1.317, 1.643]} rotation={[-0.123, -0.589, -1.742]} scale={[109.135, 109.134, 109.135]} />
      <mesh geometry={nodes.Cylinder109.geometry} material={materials.Sprinkles} position={[-3.564, 1.896, 1.345]} rotation={[0.385, -0.938, 3.014]} scale={109.135} />
      <mesh geometry={nodes.Cylinder120.geometry} material={materials.Sprinkles} position={[-2.101, 2.744, -0.705]} rotation={[1.028, 0.857, 0.569]} scale={109.134} />
      <mesh geometry={nodes.Cylinder126.geometry} material={materials.Sprinkles} position={[-3.932, 2.173, 0.421]} rotation={[0.356, 0.134, 1.646]} scale={[109.134, 109.134, 109.135]} />
      <mesh geometry={nodes.Cylinder130.geometry} material={materials.Sprinkles} position={[2.827, 3.179, -2.834]} rotation={[2.867, -0.192, 2.342]} scale={109.134} />
      <mesh geometry={nodes.Cylinder131.geometry} material={materials.Sprinkles} position={[-1.646, 3.379, -2.434]} rotation={[-0.002, -0.049, -2.251]} scale={[109.135, 109.134, 109.135]} />
      <mesh geometry={nodes.Cylinder134.geometry} material={materials.Sprinkles} position={[-3.278, 2.825, -2.572]} rotation={[-2.697, 0.551, -1.831]} scale={109.134} />
      <mesh geometry={nodes.Cylinder136.geometry} material={materials.Sprinkles} position={[2.855, 2.799, -0.377]} rotation={[0.044, 0.603, -2.39]} scale={109.135} />
      <mesh geometry={nodes.Cylinder140.geometry} material={materials.Sprinkles} position={[1.798, 2.004, 2.098]} rotation={[0.369, -0.826, -1.025]} scale={[109.135, 109.134, 109.134]} />
      <mesh geometry={nodes.Cylinder142.geometry} material={materials.Sprinkles} position={[0.935, 1.404, 3.932]} rotation={[-2.235, 0.426, -0.628]} scale={109.134} />
      <mesh geometry={nodes.Cylinder143.geometry} material={materials.Sprinkles} position={[2.067, 1.661, 3.459]} rotation={[0.769, -0.918, 0.103]} scale={[109.134, 109.135, 109.134]} />
      <mesh geometry={nodes.Cylinder144.geometry} material={materials.Sprinkles} position={[2.437, 3.303, -2.362]} rotation={[0.113, 0.027, -1.557]} scale={109.135} />
      <mesh geometry={nodes.Cylinder147.geometry} material={materials.Sprinkles} position={[-2.217, 1.249, 3.222]} rotation={[-2.472, 0.229, 1.404]} scale={[109.135, 109.134, 109.135]} />
      <mesh geometry={nodes.Cylinder156.geometry} material={materials.Sprinkles} position={[-2.947, 3.102, -2.029]} rotation={[-0.111, 0.409, 0.128]} scale={[109.134, 109.134, 109.135]} />
      <mesh geometry={nodes.Cylinder157.geometry} material={materials.Sprinkles} position={[2.038, 2.974, -1.219]} rotation={[0.672, -0.486, -0.718]} scale={109.134} />
      <mesh geometry={nodes.Cylinder159.geometry} material={materials.Sprinkles} position={[1.564, 1.885, 1.793]} rotation={[-3.058, 1.007, 2.219]} scale={109.135} />
      <mesh geometry={nodes.Cylinder003.geometry} material={materials.Sprinkles} position={[3.558, 2.514, 2.033]} rotation={[0.298, 0, 0]} scale={6.468} />
      <mesh geometry={nodes.Cylinder006.geometry} material={materials.Sprinkles} position={[2.004, 1.409, 3.798]} rotation={[-2.76, 0.735, -2.274]} scale={[109.135, 109.134, 109.135]} />
      <mesh geometry={nodes.Cylinder007.geometry} material={materials.Sprinkles} position={[-2.329, 2.18, 0.582]} rotation={[-2.303, -0.465, 1.294]} scale={[109.135, 109.134, 109.134]} />
      <mesh geometry={nodes.Cylinder013.geometry} material={materials.Sprinkles} position={[3.723, 1.437, 2.831]} rotation={[0.178, -0.681, 1.754]} scale={109.134} />
      <mesh geometry={nodes.Cylinder024.geometry} material={materials.Sprinkles} position={[2.874, 2.408, 1.142]} rotation={[0.14, 0.099, 1.964]} scale={109.135} />
      <mesh geometry={nodes.Cylinder030.geometry} material={materials.Sprinkles} position={[4.528, 2.332, -0.284]} rotation={[-2.396, -0.784, 3.093]} scale={[109.134, 109.135, 109.134]} />
      <mesh geometry={nodes.Cylinder031.geometry} material={materials.Sprinkles} position={[1.798, 3.384, -2.866]} rotation={[2.99, 0.1, -2.073]} scale={109.134} />
      <mesh geometry={nodes.Cylinder034.geometry} material={materials.Sprinkles} position={[-3.989, 2.505, -1.607]} rotation={[1.723, -1.014, -1.769]} scale={[109.135, 109.135, 109.134]} />
      <mesh geometry={nodes.Cylinder035.geometry} material={materials.Sprinkles} position={[4.267, 2.398, 0.227]} rotation={[-2.636, 0.179, 0.682]} scale={[109.134, 109.135, 109.135]} />
      <mesh geometry={nodes.Cylinder044.geometry} material={materials.Sprinkles} position={[2.963, 2.995, -1.002]} rotation={[0.293, 0.291, 0.771]} scale={109.134} />
      <mesh geometry={nodes.Cylinder055.geometry} material={materials.Sprinkles} position={[-1.492, 1.615, 1.159]} rotation={[-0.678, -0.729, -2.552]} scale={[109.135, 109.135, 109.134]} />
      <mesh geometry={nodes.Cylinder060.geometry} material={materials.Sprinkles} position={[-2.005, 2.208, 0.135]} rotation={[1.052, 0.902, 2.907]} scale={109.134} />
      <mesh geometry={nodes.Cylinder073.geometry} material={materials.Sprinkles} position={[4.448, 1.665, 1.652]} rotation={[1.674, 0.671, -0.527]} scale={[109.134, 109.135, 109.135]} />
      <mesh geometry={nodes.Cylinder074.geometry} material={materials.Sprinkles} position={[-1.689, 3.135, -1.6]} rotation={[0.65, 1.111, -1.28]} scale={[109.135, 109.135, 109.134]} />
      <mesh geometry={nodes.Cylinder076.geometry} material={materials.Sprinkles} position={[3.809, 1.838, 2.234]} rotation={[2.894, 0.897, 3.051]} scale={[109.134, 109.135, 109.134]} />
      <mesh geometry={nodes.Cylinder082.geometry} material={materials.Sprinkles} position={[-1.311, 2.818, -1.234]} rotation={[-2.572, 0.395, 1.918]} scale={[109.135, 109.134, 109.135]} />
      <mesh geometry={nodes.Cylinder084.geometry} material={materials.Sprinkles} position={[-2.338, 2.593, -0.286]} rotation={[0.529, -0.927, -0.499]} scale={[109.135, 109.135, 109.134]} />
      <mesh geometry={nodes.Cylinder091.geometry} material={materials.Sprinkles} position={[3.162, 2.115, 2.189]} rotation={[0.458, -0.004, -0.451]} scale={109.134} />
      <mesh geometry={nodes.Cylinder092.geometry} material={materials.Sprinkles} position={[2.603, 3.034, -1.167]} rotation={[-2.425, -1.314, 0.57]} scale={109.135} />
      <mesh geometry={nodes.Cylinder093.geometry} material={materials.Sprinkles} position={[-4.624, 1.205, 1.084]} rotation={[-0.264, 0.506, 0.89]} scale={[109.135, 109.134, 109.134]} />
      <mesh geometry={nodes.Cylinder094.geometry} material={materials.Sprinkles} position={[0.106, 1.657, 2.667]} rotation={[-0.178, 0.332, -1.697]} scale={109.134} />
      <mesh geometry={nodes.Cylinder096.geometry} material={materials.Sprinkles} position={[2.158, 1.887, 3.011]} rotation={[0.222, 1.322, -2.914]} scale={[109.135, 109.135, 109.134]} />
      <mesh geometry={nodes.Cylinder099.geometry} material={materials.Sprinkles} position={[-3.451, 2.875, -1.485]} rotation={[-2.659, 0.728, -2.213]} scale={109.134} />
      <mesh geometry={nodes.Cylinder111.geometry} material={materials.Sprinkles} position={[-3.188, 2.06, 1.177]} rotation={[-2.625, 0.862, 2.933]} scale={[109.135, 109.134, 109.135]} />
      <mesh geometry={nodes.Cylinder112.geometry} material={materials.Sprinkles} position={[3.364, 2.417, 1.172]} rotation={[3.063, 0.683, -3.073]} scale={[109.134, 109.135, 109.134]} />
      <mesh geometry={nodes.Cylinder113.geometry} material={materials.Sprinkles} position={[0.907, 3.396, -2.493]} rotation={[-0.039, -1.172, -2.698]} scale={109.134} />
      <mesh geometry={nodes.Cylinder114.geometry} material={materials.Sprinkles} position={[-2.718, 2.012, 1.301]} rotation={[0.48, 0.26, -1.181]} scale={[109.135, 109.134, 109.134]} />
      <mesh geometry={nodes.Cylinder116.geometry} material={materials.Sprinkles} position={[4.11, 2.659, -0.631]} rotation={[-0.028, -0.41, 0.278]} scale={[109.134, 109.135, 109.135]} />
      <mesh geometry={nodes.Cylinder121.geometry} material={materials.Sprinkles} position={[-1.388, 3.365, -3.227]} rotation={[0.616, 1.433, -1.366]} scale={[109.135, 109.135, 109.134]} />
      <mesh geometry={nodes.Cylinder123.geometry} material={materials.Sprinkles} position={[1.141, 1.15, 4.204]} rotation={[0.828, -0.141, 1.689]} scale={[109.134, 109.134, 109.135]} />
      <mesh geometry={nodes.Cylinder124.geometry} material={materials.Sprinkles} position={[3.437, 2.88, -0.681]} rotation={[0.217, 1.337, 2.058]} scale={[109.135, 109.135, 109.134]} />
      <mesh geometry={nodes.Cylinder132.geometry} material={materials.Sprinkles} position={[-1.404, 2.055, -0.42]} rotation={[-2.701, 0.349, -1.649]} scale={109.134} />
      <mesh geometry={nodes.Cylinder133.geometry} material={materials.Sprinkles} position={[0.73, 2.857, -1.476]} rotation={[1.152, 1.271, 0.022]} scale={109.135} />
      <mesh geometry={nodes.Cylinder135.geometry} material={materials.Sprinkles} position={[-0.288, 3.342, -2.265]} rotation={[0.357, -0.539, 1.047]} scale={109.134} />
      <mesh geometry={nodes.Cylinder146.geometry} material={materials.Sprinkles} position={[-1.44, 1.341, 3.429]} rotation={[0.403, -0.677, 2.458]} scale={[109.135, 109.135, 109.134]} />
      <mesh geometry={nodes.Cylinder149.geometry} material={materials.Sprinkles} position={[-0.113, 1.516, 3.545]} rotation={[2.834, -1.382, -2.268]} scale={[109.135, 109.135, 109.134]} />
      <mesh geometry={nodes.Cylinder161.geometry} material={materials.Sprinkles} position={[-3.236, 0.991, 2.939]} rotation={[1.55, -0.578, 0.555]} scale={109.134} />
      <mesh geometry={nodes.Cylinder162.geometry} material={materials.Sprinkles} position={[-1.137, 0.447, 4.394]} rotation={[2.68, -1.117, 1.223]} scale={109.135} />
      <mesh geometry={nodes.Cylinder163.geometry} material={materials.Sprinkles} position={[-0.866, 2.519, -1.14]} rotation={[3.095, 1.222, 1.63]} scale={109.135} />
      <mesh geometry={nodes.Donut001.geometry} material={materials['Material.002']} position={[0.166, 0.529, -0.278]} rotation={[0.385, 0, 0]} scale={77.953}>
        <mesh geometry={nodes.Icing001.geometry} material={materials['Material.006']} position={[0, -0.204, 0]} />
      </mesh>
    </group>
  )
}

useGLTF.preload('/donut.glb')
